# Практическое задание

__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [1]:
import numpy as np

In [2]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

In [3]:
a = np.array([[-1, 0], [0, -1]])

In [4]:
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v[:, 0]}, {v[:, 1]}\n')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]

Собственные векторы:
[1. 0.], [0. 1.]



$$A=-1*\begin{pmatrix}
1 & 0\\ 
0 & 1
\end{pmatrix}.\begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix} = \lambda \begin{pmatrix}
x_1\\ 
x_2
\end{pmatrix}, \lambda = -1$$

Справедливо для любого вектора

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



In [5]:
A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')
print(f'\nlambda = {w[1]}, x1 = {round(v[0, 1] / v[1,1], 2)} * x2')
print(f'lambda = {w[0]}, x1 = {round(v[0, 0] / v[1,0], 2)} * x2')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2.00000002 1.99999998]

lambda = 1.9999999789265757, x1 = 1.0 * x2
lambda = 2.0000000210734243, x1 = 1.0 * x2


Ответ: Вектор x=(1,1) является собственным вектором линейного оператора, заданного матрицей A.

**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [6]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]


Ответ: вектор x=(3, -3, -4) не является собственным вектором линейного оператора A.