### Pandas

In [ ]:
import pandas as pd

In [ ]:
# загружаем данные
data = pd.read_csv('gb/Airbnb_Open_Data.csv')
data.head()

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718   
1  1002102                             Skylit Midtown Castle  52335172823   
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556   
3  1002755                                               NaN  85098326012   
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077   

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington   
1               verified     Jenna           Manhattan       Midtown   
2                    NaN     Elise           Manhattan        Harlem   
3            unconfirmed     Garry            Brooklyn  Clinton Hill   
4               verified    Lyndon           Manhattan   East Harlem   

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0   
1  40.75362 -73.98377  United States  ...        $28            30.0   
2  40.80902 -73.94190  United States  ...       $124             3.0   
3  40.68514 -73.95976  United States  ...        $74            30.0   
4  40.79851 -73.94399  United States  ...        $41            10.0   

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0   
1              45.0   5/21/2022               0.38                4.0   
2               0.0         NaN                NaN                5.0   
3             270.0    7/5/2019               4.64                4.0   
4               9.0  11/19/2018               0.10                3.0   

  calculated host listings count  availability 365  \
0                            6.0             286.0   
1                            2.0             228.0   
2                            1.0             352.0   
3                            1.0             322.0   
4                            1.0             289.0   

                                         house_rules license  
0  Clean up and treat the home the way you'd like...     NaN  
1  Pet friendly but please confirm with me if the...     NaN  
2  I encourage you to use my kitchen, cooking and...     NaN  
3                                                NaN     NaN  
4  Please no smoking in the house, porch or on th...     NaN  

[5 rows x 26 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   id                              102599 non-null  int64  
 1   NAME                            102349 non-null  object 
 2   host id                         102599 non-null  int64  
 3   host_identity_verified          102310 non-null  object 
 4   host name                       102193 non-null  object 
 5   neighbourhood group             102570 non-null  object 
 6   neighbourhood                   102583 non-null  object 
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object 
 10  country code                    102468 non-null  object 
 11  instant_bookable                102494 non-null  object 
 12  cancellation_pol

In [ ]:
data.shape

(102599, 26)

In [ ]:
data.describe()

id       host id            lat           long  \
count  1.025990e+05  1.025990e+05  102591.000000  102591.000000   
mean   2.914623e+07  4.925411e+10      40.728094     -73.949644   
std    1.625751e+07  2.853900e+10       0.055857       0.049521   
min    1.001254e+06  1.236005e+08      40.499790     -74.249840   
25%    1.508581e+07  2.458333e+10      40.688740     -73.982580   
50%    2.913660e+07  4.911774e+10      40.722290     -73.954440   
75%    4.320120e+07  7.399650e+10      40.762760     -73.932350   
max    5.736742e+07  9.876313e+10      40.916970     -73.705220   

       Construction year  minimum nights  number of reviews  \
count      102385.000000   102190.000000      102416.000000   
mean         2012.487464        8.135845          27.483743   
std             5.765556       30.553781          49.508954   
min          2003.000000    -1223.000000           0.000000   
25%          2007.000000        2.000000           1.000000   
50%          2012.000000        3.000000           7.000000   
75%          2017.000000        5.000000          30.000000   
max          2022.000000     5645.000000        1024.000000   

       reviews per month  review rate number  calculated host listings count  \
count       86720.000000       102273.000000                   102280.000000   
mean            1.374022            3.279106                        7.936605   
std             1.746621            1.284657                       32.218780   
min             0.010000            1.000000                        1.000000   
25%             0.220000            2.000000                        1.000000   
50%             0.740000            3.000000                        1.000000   
75%             2.000000            4.000000                        2.000000   
max            90.000000            5.000000                      332.000000   

       availability 365  
count     102151.000000  
mean         141.133254  
std          135.435024  
min          -10.000000  
25%            3.000000  
50%           96.000000  
75%          269.000000  
max         3677.000000

In [ ]:
data.rename(columns={"NAME": "name"}, inplace=True)
data.head()

id                                              name      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718   
1  1002102                             Skylit Midtown Castle  52335172823   
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556   
3  1002755                                               NaN  85098326012   
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077   

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington   
1               verified     Jenna           Manhattan       Midtown   
2                    NaN     Elise           Manhattan        Harlem   
3            unconfirmed     Garry            Brooklyn  Clinton Hill   
4               verified    Lyndon           Manhattan   East Harlem   

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0   
1  40.75362 -73.98377  United States  ...        $28            30.0   
2  40.80902 -73.94190  United States  ...       $124             3.0   
3  40.68514 -73.95976  United States  ...        $74            30.0   
4  40.79851 -73.94399  United States  ...        $41            10.0   

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0   
1              45.0   5/21/2022               0.38                4.0   
2               0.0         NaN                NaN                5.0   
3             270.0    7/5/2019               4.64                4.0   
4               9.0  11/19/2018               0.10                3.0   

  calculated host listings count  availability 365  \
0                            6.0             286.0   
1                            2.0             228.0   
2                            1.0             352.0   
3                            1.0             322.0   
4                            1.0             289.0   

                                         house_rules license  
0  Clean up and treat the home the way you'd like...     NaN  
1  Pet friendly but please confirm with me if the...     NaN  
2  I encourage you to use my kitchen, cooking and...     NaN  
3                                                NaN     NaN  
4  Please no smoking in the house, porch or on th...     NaN  

[5 rows x 26 columns]

In [ ]:
data.duplicated().sum()

541

In [ ]:
data['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [ ]:
data['country'].unique()

array(['United States', nan], dtype=object)

In [ ]:
data['room type'].unique()

array(['Private room', 'Entire home/apt', 'Shared room', 'Hotel room'],
      dtype=object)

In [ ]:
data.isnull().sum()

id                                     0
name                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules     

In [ ]:
data[data['room type'] == 'Private room'].head()

id                                 name      host id  \
0  1001254   Clean & quiet apt home by the park  80014485718   
2  1002403  THE VILLAGE OF HARLEM....NEW YORK !  78829239556   
6  1004650                      BlissArtsSpace!  61300605564   
7  1005202                      BlissArtsSpace!  90821839709   
8  1005754      Large Furnished Room Near B'way  79384379533   

  host_identity_verified host name neighbourhood group       neighbourhood  \
0            unconfirmed  Madaline            Brooklyn          Kensington   
2                    NaN     Elise           Manhattan              Harlem   
6                    NaN   Alberta            Brooklyn  Bedford-Stuyvesant   
7            unconfirmed      Emma            Brooklyn  Bedford-Stuyvesant   
8               verified    Evelyn           Manhattan      Hell's Kitchen   

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0   
2  40.80902 -73.94190  United States  ...       $124             3.0   
6  40.68688 -73.95596  United States  ...        $14            45.0   
7  40.68688 -73.95596  United States  ...       $212            45.0   
8  40.76489 -73.98493  United States  ...       $204             2.0   

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0   
2               0.0         NaN                NaN                5.0   
6              49.0   10/5/2017               0.40                5.0   
7              49.0   10/5/2017               0.40                5.0   
8             430.0   6/24/2019               3.47                3.0   

  calculated host listings count  availability 365  \
0                            6.0             286.0   
2                            1.0             352.0   
6                            1.0             224.0   
7                            1.0             219.0   
8                            1.0             180.0   

                                         house_rules license  
0  Clean up and treat the home the way you'd like...     NaN  
2  I encourage you to use my kitchen, cooking and...     NaN  
6  Please no shoes in the house so bring slippers...     NaN  
7  House Guidelines for our BnB We are delighted ...     NaN  
8  - Please clean up after yourself when using th...     NaN  

[5 rows x 26 columns]

In [ ]:
data[data['minimum nights'] > 70][['name', 'minimum nights', 'price']].head()

name  minimum nights  price
15                       West Village Nest - Superhost            90.0  $578 
62                                                 NaN           180.0  $779 
107                  Large 2 Bedroom Great for Groups!            90.0  $500 
165    Charming & Cozy midtown loft any WEEK ENDS  !!!            81.0  $950 
166  * Spacious GARDEN Park Slope Duplex* 6 people max           144.0  $374

In [ ]:
data[(data['minimum nights'] > 70) & (data['neighbourhood group'] == 'Brooklyn')].head()

id                                               name      host id  \
107  1060432                  Large 2 Bedroom Great for Groups!  94662871331   
166  1093018  * Spacious GARDEN Park Slope Duplex* 6 people max  61571782497   
169  1094675                     House On Henry (2nd FLR Suite)  44408473243   
171  1095779                Sunny cozy room in Brklyn townhouse  29877853006   
181  1101302              Fort Greene, Brooklyn: Center Bedroom   9549678609   

    host_identity_verified host name neighbourhood group       neighbourhood  \
107            unconfirmed      Tess            Brooklyn  Bedford-Stuyvesant   
166               verified    Nicole            Brooklyn             Gowanus   
169                    NaN     James            Brooklyn     Carroll Gardens   
171                    NaN     Jared            Brooklyn            Bushwick   
181            unconfirmed     Adele            Brooklyn         Fort Greene   

          lat      long        country  ... service fee minimum nights  \
107  40.68373 -73.92377  United States  ...       $100            90.0   
166  40.66858 -73.99083  United States  ...        $75           144.0   
169  40.67830 -74.00135  United States  ...       $168           273.0   
171  40.70641 -73.91765  United States  ...       $101           275.0   
181  40.68863 -73.97691  United States  ...        $21           350.0   

    number of reviews last review  reviews per month review rate number  \
107             162.0   6/28/2019               1.46                3.0   
166              80.0    7/6/2019                NaN                2.0   
169             150.0   6/18/2019               1.40                5.0   
171              47.0   6/19/2019               0.94                5.0   
181             206.0   6/30/2019               1.92                4.0   

    calculated host listings count  availability 365  \
107                            2.0             189.0   
166                            1.0              52.0   
169                            3.0             141.0   
171                            1.0             263.0   
181                            2.0              96.0   

                                           house_rules license  
107  - Thanks for not smoking and leaving your pets...     NaN  
166  No candles, smoking or flame of any kind is al...     NaN  
169  -Please no pets -Quiet hours are from 10pm - 8...     NaN  
171  No pets that shed; If you have a hypo-allergen...     NaN  
181  -No shoes in our home. Please leave them at th...     NaN  

[5 rows x 26 columns]

In [ ]:
data.corr()

id   host id       lat      long  \
id                              1.000000 -0.000830 -0.008832  0.042546   
host id                        -0.000830  1.000000  0.000661 -0.008999   
lat                            -0.008832  0.000661  1.000000  0.074348   
long                            0.042546 -0.008999  0.074348  1.000000   
Construction year               0.001081  0.004871  0.005697  0.000861   
minimum nights                  0.005668 -0.002266  0.014889 -0.039639   
number of reviews              -0.041530 -0.004503 -0.025236  0.069169   
reviews per month               0.038038 -0.001746 -0.019492  0.118598   
review rate number              0.036633  0.003459 -0.003917  0.015283   
calculated host listings count  0.024296  0.001722  0.032468 -0.104154   
availability 365               -0.139226 -0.002044 -0.005011  0.058428   

                                Construction year  minimum nights  \
id                                       0.001081        0.005668   
host id                                  0.004871       -0.002266   
lat                                      0.005697        0.014889   
long                                     0.000861       -0.039639   
Construction year                        1.000000       -0.000486   
minimum nights                          -0.000486        1.000000   
number of reviews                        0.001990       -0.049997   
reviews per month                        0.004092       -0.096141   
review rate number                       0.004753       -0.002167   
calculated host listings count          -0.002745        0.084846   
availability 365                        -0.008264        0.063541   

                                number of reviews  reviews per month  \
id                                      -0.041530           0.038038   
host id                                 -0.004503          -0.001746   
lat                                     -0.025236          -0.019492   
long                                     0.069169           0.118598   
Construction year                        0.001990           0.004092   
minimum nights                          -0.049997          -0.096141   
number of reviews                        1.000000           0.590939   
reviews per month                        0.590939           1.000000   
review rate number                      -0.018412           0.037526   
calculated host listings count          -0.080907          -0.025621   
availability 365                         0.099368           0.077193   

                                review rate number  \
id                                        0.036633   
host id                                   0.003459   
lat                                      -0.003917   
long                                      0.015283   
Construction year                         0.004753   
minimum nights                           -0.002167   
number of reviews                        -0.018412   
reviews per month                         0.037526   
review rate number                        1.000000   
calculated host listings count            0.024273   
availability 365                         -0.006217   

                                calculated host listings count  \
id                                                    0.024296   
host id                                               0.001722   
lat                                                   0.032468   
long                                                 -0.104154   
Construction year                                    -0.002745   
minimum nights                                        0.084846   
number of reviews                                    -0.080907   
reviews per month                                    -0.025621   
review rate number                                    0.024273   
calculated host listings count                        1.000000   
availability 365                                      0.159194   

             

In [ ]:
data['availability'] = data['availability 365'] / 365 * 100
data.head()

id                                              name      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718   
1  1002102                             Skylit Midtown Castle  52335172823   
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556   
3  1002755                                               NaN  85098326012   
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077   

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington   
1               verified     Jenna           Manhattan       Midtown   
2                    NaN     Elise           Manhattan        Harlem   
3            unconfirmed     Garry            Brooklyn  Clinton Hill   
4               verified    Lyndon           Manhattan   East Harlem   

        lat      long        country  ... minimum nights number of reviews  \
0  40.64749 -73.97237  United States  ...           10.0               9.0   
1  40.75362 -73.98377  United States  ...           30.0              45.0   
2  40.80902 -73.94190  United States  ...            3.0               0.0   
3  40.68514 -73.95976  United States  ...           30.0             270.0   
4  40.79851 -73.94399  United States  ...           10.0               9.0   

  last review reviews per month  review rate number  \
0  10/19/2021              0.21                 4.0   
1   5/21/2022              0.38                 4.0   
2         NaN               NaN                 5.0   
3    7/5/2019              4.64                 4.0   
4  11/19/2018              0.10                 3.0   

  calculated host listings count availability 365  \
0                            6.0            286.0   
1                            2.0            228.0   
2                            1.0            352.0   
3                            1.0            322.0   
4                            1.0            289.0   

                                         house_rules  license availability  
0  Clean up and treat the home the way you'd like...      NaN    78.356164  
1  Pet friendly but please confirm with me if the...      NaN    62.465753  
2  I encourage you to use my kitchen, cooking and...      NaN    96.438356  
3                                                NaN      NaN    88.219178  
4  Please no smoking in the house, porch or on th...      NaN    79.178082  

[5 rows x 27 columns]

In [ ]:
data.groupby(['neighbourhood group'])['id'].count()

neighbourhood group
Bronx             2712
Brooklyn         41842
Manhattan        43792
Queens           13267
Staten Island      955
brookln              1
manhatan             1
Name: id, dtype: int64

In [ ]:
data['neighbourhood group'] = data['neighbourhood group'].replace({'brookln': 'Brooklyn'})
data['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [ ]:
data

id                                              name  \
0       1001254                Clean & quiet apt home by the park   
1       1002102                             Skylit Midtown Castle   
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !   
3       1002755                                               NaN   
4       1003689  Entire Apt: Spacious Studio/Loft by central park   
...         ...                                               ...   
102594  6092437                        Spare room in Williamsburg   
102595  6092990                     Best Location near Columbia U   
102596  6093542                    Comfy, bright room in Brooklyn   
102597  6094094                  Big Studio-One Stop from Midtown   
102598  6094647                              585 sf Luxury Studio   

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn   
1       52335172823               verified        Jenna           Manhattan   
2       78829239556                    NaN        Elise           Manhattan   
3       85098326012            unconfirmed        Garry            Brooklyn   
4       92037596077               verified       Lyndon           Manhattan   
...             ...                    ...          ...                 ...   
102594  12312296767               verified         Krik            Brooklyn   
102595  77864383453            unconfirmed        Mifan           Manhattan   
102596  69050334417            unconfirmed        Megan            Brooklyn   
102597  11160591270            unconfirmed  Christopher              Queens   
102598  68170633372            unconfirmed      Rebecca           Manhattan   

              neighbourhood       lat      long        country  ...  \
0                Kensington  40.64749 -73.97237  United States  ...   
1                   Midtown  40.75362 -73.98377  United States  ...   
2                    Harlem  40.80902 -73.94190  United States  ...   
3              Clinton Hill  40.68514 -73.95976  United States  ...   
4               East Harlem  40.79851 -73.94399  United States  ...   
...                     ...       ...       ...            ...  ...   
102594         Williamsburg  40.70862 -73.94651  United States  ...   
102595  Morningside Heights  40.80460 -73.96545  United States  ...   
102596           Park Slope  40.67505 -73.98045  United States  ...   
102597     Long Island City  40.74989 -73.93777  United States  ...   
102598      Upper West Side  40.76807 -73.98342  United States  ...   

       minimum nights number of reviews last review reviews per month  \
0                10.0               9.0  10/19/2021              0.21   
1                30.0              45.0   5/21/2022              0.38   
2                 3.0               0.0         NaN               NaN   
3                30.0             270.0    7/5/2019              4.64   
4                10.0               9.0  11/19/2018              0.10   
...               ...               ...         ...               ...   
102594            1.0               0.0         NaN               NaN   
102595            1.0               1.0    7/6/2015              0.02   
102596            3.0               0.0         NaN               NaN   
102597            2.0               5.0  10/11/2015              0.10   
102598            1.0               0.0         NaN               NaN   

        review rate number calculated host listings count availability 365  \
0                      4.0                            6.0            286.0   
1                      4.0                            2.0            228.0   
2                      5.0                            1.0            352.0   
3                      4.0                            1.0            322.0   
4                      3.0                            1.0            289.0   
...                    ...           

## NumPy

In [ ]:
import numpy as np

### 1. Одномерные массивы

In [ ]:
a = np.array([0, 2, 1])
a, type(a)

(array([0, 2, 1]), numpy.ndarray)

In [ ]:
a.shape

(3,)

In [ ]:
len(a), a.size

(3, 3)

In [ ]:
a = np.zeros(3)
b = np.ones(3, dtype=np.int64)
a, b

(array([0., 0., 0.]), array([1, 1, 1]))

In [ ]:
a = np.arange(0, 9, 2)
a

array([0, 2, 4, 6, 8])

### 1.1 Операции над одномерными массивами

In [ ]:
a = np.arange(0, 9, 2)
b = np.arange(10, 20, 2)
a, b

(array([0, 2, 4, 6, 8]), array([10, 12, 14, 16, 18]))

In [ ]:
a + b

array([10, 14, 18, 22, 26])

In [ ]:
a - b

array([-10, -10, -10, -10, -10])

In [ ]:
a / b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [ ]:
b * (-1)

array([-10, -12, -14, -16, -18])

In [ ]:
a > b

array([False, False, False, False, False])

In [ ]:
# объединение массивов
np.hstack((a, b))

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# добавление элементов
np.append(a, [1, 2, 3])

array([0, 2, 4, 6, 8, 1, 2, 3])

In [ ]:
# срезы
a[2:6], a[1:4:2]

(array([4, 6, 8]), array([2, 6]))

### 2. Двумерные массивы массивы

In [ ]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
a

array([[ 0.,  1.],
       [-1.,  0.]])

In [ ]:
a.shape, len(a), a.size

((2, 2), 2, 4)

In [ ]:
a.ravel()

array([ 0.,  1., -1.,  0.])

In [ ]:
a + 1

array([[1., 2.],
       [0., 1.]])

In [ ]:
a / 2

array([[ 0. ,  0.5],
       [-0.5,  0. ]])

### 2.2 Работа с матрицами

In [ ]:
a = np.array([[-3, 4], [4, 3]])
b = np.array([[2, 1], [1, 2]])
a, b

(array([[-3,  4],
        [ 4,  3]]),
 array([[2, 1],
        [1, 2]]))

In [ ]:
# поэлементное умножение
a * b

array([[-6,  4],
       [ 4,  6]])

In [ ]:
# умножение матриц
a @ b

array([[-2,  5],
       [11, 10]])

In [ ]:
a.dot(b)

array([[-2,  5],
       [11, 10]])

### 3. Тензоры

In [ ]:
x = np.arange(24).reshape(2, 3, 4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
x.shape

(2, 3, 4)

### 4. Линейная алгебра

In [ ]:
a = np.array([[0, 1], [2, 3]])
a

NameError: ignored

In [ ]:
# определитель матрицы
np.linalg.det(a)

In [ ]:
# обратная матрица
np.linalg.inv(a)

In [ ]:
# собственные значения
np.linalg.eig(a)